services:
  nextjs:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
    command: npm run dev
    tty: true
    stdin_open: true
